UNKNOWN_COUNTRY = "Unknown-Country"
COUNTRY = {
    "西欧":{
        "英国":["England","English","UK"],
        "法国":["France"],
        "意大利":[],
        "德国":[],
        "瑞士":[],
        "比利时":[],
        "西班牙":[],
    },
    "北欧":{
        "荷兰":[],
        "瑞典":[],
        "丹麦":[],
        "挪威":[],
        "爱沙尼亚":[],
    },
    "东欧":{
        "俄罗斯":[],
        "白俄罗斯":[],
        "乌克兰":[]
    },
    "南欧":{
        "希腊":[]
    },
    "北美":{
        "美国":["USA","America","American","United States"],
        "加拿大":[],
        "古巴":[],
        "墨西哥":[]
    },
    "南美":{
       "阿根廷":[],
        "巴西":[] 
    },
    "亚洲":{
        "韩国":[],
        "内地":[],
        "日本":["Japan"],
        "台湾":[],
        "香港":[],
        "马来西亚":[]
    },
    "岛国":{
        "冰岛":[],
        "新西兰":[],
        "澳大利亚":[]
    }
}

UNKNOWN_GENRE = "Unknown-Genre"
GENERE = [
    {
        "Punk":[],
        "Post-Punk":[],
        "Electro-Punk":[],
        "Grunge":[],
    },
    {
        "Metal":[],
        "Post-Metal":[],
        "Avant-Metal":[],
        "Melodic-Metal":[],
        "Doom-Metal":[],
    },
    {
        "Death-Core":[],
        "Slow-Core":[],
        "Grind-Core":[]
    },
    {
        "Rock":[],
        "Indie-Rock":["独立摇滚"],
        "Garage-Rock":[],
        "Alternative-Rock":[],
        "Experimental-Rock":[],
        "Shoegaze":["盯鞋"],
        "Math-Rock":[],
        "Glam-Rock":[],
        "Brit-Rock":[],
        "J-Rock":[],
        "Psycho-Rock":[],
        "Surf-Rock":[],
        "Avant-Rock":[]
    },
    {
        "New-Wave":[],
        "Cold-Wave":[],
        "Dark-Wave":[]
    },
    {
        "Folk":[],
        "Indie-Folk":[],
        "Death-Folk":[]
    },
    {
        "Instrumental":[],
        "Classical":[],
        "Neo-Classical":[]
    },
    {
        "Pop":[],
        "Indie-Pop":[],
        "J-Pop":[],
        "City-Pop":[],
        "Noise-Pop":[],
        "Brit-Pop":[],
        "Synth-Pop":[],
        "Electronic-Pop":[],
        "Dream-Pop":["梦泡"],
        "Psychedelic-Pop":[],
        "R&B":[]
    },
    {
        "Rap":[],
        "Trap-Rap":[],
        "Alternative-Rap":[],
        "Melody-Rap":[],
        "Mumble-Rap":[],
        "Alternative-Trap":[],
    },
    {
        "Electronic":[],
        "Trance":[],
        "Dubstep":[],
        "Trap":[],
        "Indie-Electronic":[],
        "Experimental-Eletronic":[],
    },
    {
        "Jazz":[],
        "Electronic-Jazz":[],
        "Jazz-Pop":[],
        "Jazz-Rock":[],
        "Jazztronica":[],
        "Acid-Jazz":[],
        "Nu-Jazz":[],
        "Bossa-Nova":[],
    },
    {
        "World-Music":[],
        "OST":[],
        "New-Age":[],
        "Tango":[],
        "Funk":[],
        "Experimental-Funk":[],
        "Latin":[],
        "Flamenco":[],
        "Trip-Hop":[],
    },
    {
        "Experimental":[],
        "Ambient":["ambient"],
        "Gothic":[],
        "Blues":[],
        "Country":[],
    }
]